# Generated by Django 2.2.4 on 2020-01-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='content',
            new_name='contents',
        ),
    ]
