# Generated by Django 2.2.4 on 2020-01-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
